### PR TITLE
Distinguish parsing failures from conversion failures in ConfigReaderException

### LINKED ISSUE #190: Print parsing errors in a special way in ConfigReaderException
When reviewing #181 I noticed that both parsing errors and errors in the root file are printed in the same way - as neither of them has a config path defined, they are shown to be just "in the configuration". But in reality, they correspond to different kinds of "in the configuration". While, say, finding a list instead of an object in the root of the configuration is a localized error (it happens in the root path), a parsing error is a different thing altogether - logically, it happens on a previous phase than all the other "schema" failures currently in pureconfig.

We should distinguish these type of failures. I don't think it is worth it to distinguish them using different types, given the necessary increase in the complexity of the model. However, I'd like to see distinct error messages in those cases when a `ConfigReaderException` is thrown.

One way to easily solve it is to set the `path` of a non-`CannotParse` failure as `Some("")` when it happens at the root, distinguishing them from errors with undefined or unknown paths with `path == None`. `ConfigReaderException` would then deal with it in a special way (for example, printing "at the root" instead of "at ${path}".

### PR DESCRIPTION
**Pull request by jcazevedo**
This PR proposes a distinction between parsing failures and conversion failures, mainly to make it clearer in the `ConfigReaderException` message what errors happened at the root of the configuration and what errors were raised due to an inability to parse the configuration.

This fixes #190.

### CODE REVIEW

File: core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala [hunk 1]
```diff
@@ -58,24 +58,19 @@ object ConfigValueLocation {
 
 /**
  * A representation of a failure that might be raised from reading a
- * ConfigValue. The failure contains an optional location of the ConfigValue
- * that raised the error.
+ * ConfigValue. The failure contains an optional physical location of the
```
Comment (ruippeixotog) [inline core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala]: Minor suggestion: "physical location" is a bit strange. Consider changing to "file system location".

**Review by ruippeixotog — APPROVED** [review]
LGTM!

File: core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala (hunk 1 above)
Comment (jcazevedo) [reply core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala]: Changed it to "file system location" in 6d3a463.

File: core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala [hunk 2]
```diff
@@ -106,14 +114,14 @@ final case object CannotConvertNull extends ConfigReaderFailure {
  * @param because the reason why the conversion was not possible
  * @param location an optional location of the ConfigValue that raised the
  *                 failure
- * @param path an optional path to the value that couldn't be converted
+ * @param path thet path to the value that couldn't be converted
```
Comment (melrief) [inline core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala]: Typo `s/thet/the`

**Review by melrief — APPROVED** [review]
LGTM, just fix the typo

File: core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala (hunk 2 above)
Comment (jcazevedo) [reply core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala]: Thanks! Fixed the typo in ea16b58.

**Review by derekmorr — APPROVED** [review]
