### PR TITLE
Extract `ConfigReaderException` pretty printing logic to `ConfigReaderFailures`

### LINKED ISSUE #385: Move `ConfigReaderFailures` pretty printing logic away from `ConfigReaderException`
Here's my problem: I want to load a config in a safe way (without throwing exceptions) and log the errors in a pretty error messages.

Right now, it appears that the two best ways to do this are:
* Use `loadConfig[Config](config, "field")` and write my own `ConfigReaderFailures` pretty printer;
* Use `Try(loadConfigOrThrow[Config](config, "field"))` and log the exception message;

I think that the pretty printing logic could be moved to the `ConfigReaderFailures`.

It might also be nice to add a `Show` implementation to the cats module (or maybe not, not sure if this is out of the scope of that module).

### PR DESCRIPTION
**Pull request by JD557**
Extracts the bulk of the `ConfigReaderException` pretty printing logic to a `prettyPrint` method on `ConfigReaderFailures` (with configurable spacing).

Closes #385

### CODE REVIEW

File: core/src/main/scala/pureconfig/error/ConfigReaderFailures.scala [hunk 1]
```diff
@@ -15,6 +17,37 @@ case class ConfigReaderFailures(head: ConfigReaderFailure, tail: List[ConfigRead
 
   def ++(that: ConfigReaderFailures): ConfigReaderFailures =
     new ConfigReaderFailures(head, tail ++ that.toList)
+
+  def prettyPrint(identLevel: Int = 0, tabSize: Int = 2): String = {
```
Comment (leifwickland) [inline core/src/main/scala/pureconfig/error/ConfigReaderFailures.scala]: Nitpick: I'd prefer to rename `tabSize` to `indentSize`.

**Review by leifwickland — APPROVED** [review]
@JD557 Thanks for doing this. It's a change I've wanted for a while.

Did you check if it'd make sense to add any tests now that `prettyPrint` is accessible?

File: core/src/main/scala/pureconfig/error/ConfigReaderFailures.scala (hunk 1 above)
Comment (JD557) [reply core/src/main/scala/pureconfig/error/ConfigReaderFailures.scala]: Renamed in 5f420d0

**Comment by JD557** [comment]
>Did you check if it'd make sense to add any tests now that prettyPrint is accessible?

I think that most pretty printing logic is already tested by the `ConfigReaderExceptionSuite`.

Nevertheless, I added some basic tests in 023f219 to a new `ConfigReaderFailuresPrettyPrintSuite` that simply checks if the identation is correctly applied.

**Comment by leifwickland** [comment]
Thanks for adding the test @JD557. We'll wait for another maintainer to approve before merging.

**Review by ruippeixotog — COMMENTED** [review]
@JD557 looks good, thanks for doing this!

> I think that most pretty printing logic is already tested by the ConfigReaderExceptionSuite

Nit: because we've moved this logic to another class, I'd prefer that you also moved the pretty printing logic tests to `ConfigReaderFailuresPrettyPrintSuite`, as we're not really testing the exception anymore. What do you think?

**Review by jcazevedo — APPROVED** [review]
@JD557: Looks good! Thanks for this!

I agree with @ruippeixotog about moving the tests related to the pretty printing logic from `ConfigReaderExceptionSuite` to `ConfigReaderFailuresPrettyPrintSuite`.

In the scope of #385, it'd also be nice to have access to the string representation (with location) of individual `ConfigReaderFailure`s, but that can be left for future work.

**Comment by JD557** [comment]
>Nit: because we've moved this logic to another class, I'd prefer that you also moved the pretty printing logic tests to ConfigReaderFailuresPrettyPrintSuite, as we're not really testing the exception anymore. What do you think?

Done in 6aef1c9 (I think I moved everything).

I left the first pretty print test `ConfigReaderExceptionSuite` on purpose, to check that the exception message is actually using the pretty printer.

**Review by ruippeixotog — APPROVED** [review]
Excellent, thanks again!
