### PR TITLE
Make ConfigConvertWrapper return a failure if a Path cannot be read

### LINKED ISSUE #244: parseFile and loadFile doesn't fail if the file doesn't exist

### PR DESCRIPTION
**Pull request by ruippeixotog**
Fixes #244.

### CODE REVIEW

File: core/src/main/scala/pureconfig/backend/ConfigFactoryWrapper.scala [hunk 1]
```diff
@@ -22,15 +22,17 @@ object ConfigFactoryWrapper {
     unsafeToEither(ConfigFactory.load())
 
   /** @see `com.typesafe.config.ConfigFactory.parseFile()` */
-  def parseFile(path: Path): Either[ConfigReaderFailures, Config] =
-    unsafeToEither(ConfigFactory.parseFile(path.toFile))
+  def parseFile(path: Path): Either[ConfigReaderFailures, Config] = {
+    if (!path.toFile.isFile || !path.toFile.canRead) Left(ConfigReaderFailures(CannotReadFile(path)))
```
Comment (ruippeixotog) [inline core/src/main/scala/pureconfig/backend/ConfigFactoryWrapper.scala]: This check catches many common cases, but it does not ensure that the file can indeed be read. The only sure way to know that is reading the file ourselves and pass its contents to `ConfigFactory.parseString`, but then we would need to care with other things, like dealing with charsets. Do you think this check is enough, at least for now?

Comment (derekmorr) [inline core/src/main/scala/pureconfig/backend/ConfigFactoryWrapper.scala]: I wonder if it would be better to use the Java 7 NIO APIs in the conditional:

Files.isReadable(path) && Files.isRegularFile(path)

File: core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala [hunk 2]
```diff
@@ -298,6 +299,16 @@ final case class NoValidCoproductChoiceFound(value: ConfigValue, location: Optio
 }
 
 /**
+ * A failure representing the inability to read a requested file.
+ */
+final case class CannotReadFile(path: Path) extends ConfigReaderFailure {
```
Comment (derekmorr) [inline core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala:304]: Is it worth distinguishing between `path` not being a file vs not being able to read the file?

File: core/src/main/scala/pureconfig/backend/ConfigFactoryWrapper.scala (hunk 1 above)
Comment (ruippeixotog) [reply core/src/main/scala/pureconfig/backend/ConfigFactoryWrapper.scala]: Sure, I can change it to use NIO since we are already working with a `Path`. Out of curiosity, is there any functional difference in these checks between the two APIs?

File: core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala (hunk 2 above)
Comment (ruippeixotog) [reply core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala:304]: Yeah, I thought about that too. And there are more reasons why you might not be able to read a file, such as the case where a file is locked by the OS.

In this PR I didn't focus in giving the user information about exactly why the file cannot be read, but I think that would be better passed along to the user by making a general failure like `CannotReadFile` hold a `reason` string than by creating a different `Failure` for each type of IO error.

File: core/src/main/scala/pureconfig/backend/ConfigFactoryWrapper.scala (hunk 1 above)
Comment (derekmorr) [reply core/src/main/scala/pureconfig/backend/ConfigFactoryWrapper.scala]: I don't believe there's a functional difference, but if we're already using NIO, it makes sense to keep using it. It also avoids some extra allocations.

File: core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala (hunk 2 above)
Comment (derekmorr) [reply core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala:304]: Makes sense.

File: core/src/main/scala/pureconfig/backend/ConfigFactoryWrapper.scala (hunk 1 above)
Comment (ruippeixotog) [reply core/src/main/scala/pureconfig/backend/ConfigFactoryWrapper.scala]: Sure. Changed it to java.nio in 7503363.

File: core/src/test/scala/pureconfig/ConfigReaderMatchers.scala [hunk 3]
```diff
@@ -0,0 +1,16 @@
...
+import org.scalatest._
+import org.scalatest.matchers.Matcher
+import pureconfig.error.{ ConfigReaderFailure, ConfigReaderFailures }
+
+trait ConfigReaderMatchers { this: FlatSpec with Matchers =>
+
+  def failWith(failure: ConfigReaderFailure): Matcher[Either[ConfigReaderFailures, Any]] =
+    be(Left(ConfigReaderFailures(failure, Nil)))
+
+  def failWithType[Failure <: ConfigReaderFailure: ClassTag]: Matcher[Either[ConfigReaderFailures, Any]] =
```
Comment (leifwickland) [inline core/src/test/scala/pureconfig/ConfigReaderMatchers.scala:14]: This is really expressive. Nice work!

**Review by leifwickland — APPROVED** [review]
LGTM. 👍

**Review by derekmorr — APPROVED** [review]

File: core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala (hunk 2 above)
Comment (ruippeixotog) [reply core/src/main/scala/pureconfig/error/ConfigReaderFailure.scala:304]: I have just opened #248 for me to deal with this later.
